### ISSUE TITLE
UnsatisfiedLinkError on Android 5.1

### ISSUE THREAD

**Issue by vartan1988** [bytedeco/sample-projects#11]
Hello 

I try to run your example on Android 5.1.1 and when i click on Start button i get this error

```04-07 15:29:36.961 26836-26836/org.bytedeco.javacv_android_example W/linker: libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d
04-07 15:29:36.962 26836-26836/org.bytedeco.javacv_android_example W/linker: libjniavutil.so: unused DT entry: type 0x6ffffffe arg 0x221dc
04-07 15:29:36.962 26836-26836/org.bytedeco.javacv_android_example W/linker: libjniavutil.so: unused DT entry: type 0x6fffffff arg 0x1
04-07 15:29:36.963 26836-26836/org.bytedeco.javacv_android_example E/art: dlopen("/data/app/org.bytedeco.javacv_android_example-1/lib/arm/libjniavutil.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_version_info" referenced by "libjniavutil.so"...
04-07 15:29:36.982 26836-26836/org.bytedeco.javacv_android_example I/art: Rejecting re-init on previously-failed class java.lang.Class<org.bytedeco.javacpp.avutil>
04-07 15:29:36.982 26836-26836/org.bytedeco.javacv_android_example D/AndroidRuntime: Shutting down VM
04-07 15:29:36.988 26836-26836/org.bytedeco.javacv_android_example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                     Process: org.bytedeco.javacv_android_example, PID: 26836
                                                                                     java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
                                                                                         at java.lang.Class.classForName(Native Method)
                                                                                         at java.lang.Class.forName(Class.java:309)
                                                                                         at org.bytedeco.javacpp.Loader.load(Loader.java:585)
                                                                                         at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                                         at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1694)
                                                                                         at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:152)
                                                                                         at org.bytedeco.javacv.FFmpegFrameRecorder.<init>(FFmpegFrameRecorder.java:132)
                                                                                         at org.bytedeco.javacv_android_example.record.RecordActivity.initRecorder(RecordActivity.java:216)
                                                                                         at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:230)
                                                                                         at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:312)
                                                                                         at android.view.View.performClick(View.java:4789)
                                                                                         at android.view.View$PerformClick.run(View.java:19881)
                                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
04-07 15:29:36.991 2228-4100/system_process W/ActivityManager:   Force finishing activity 1 org.bytedeco.javacv_android_example/.record.RecordActivity```

**Comment by saudet** [comment]
Please try to follow the instructions in the README.md file.

**Comment by saudet** [comment]
There is also additional information for Android here:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
Let me know if that doesn't solve your issue, thanks!
