### ISSUE TITLE
org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -113: Could not open 'null'

### ISSUE THREAD

**Issue by MuthuEphron** [bytedeco/sample-projects#14]
Sir I used the rtmp url like rtmp://10.136.45.22:1935/livestream/myStream.mp4. When recorded the streaming video. I got the issue. How to recover Please solve this issue.

> 4-25 18:13:37.303 10168-10168/org.bytedeco.javacv_android_example W/linker: /data/app/org.bytedeco.javacv_android_example-2/lib/arm/libjniavutil.so: unused DT entry: type 0xf arg 0x18b9d
04-25 18:13:37.377 10168-10168/org.bytedeco.javacv_android_example W/linker: /data/app/org.bytedeco.javacv_android_example-2/lib/arm/libjniswresample.so: unused DT entry: type 0xf arg 0x2f4c
04-25 18:13:37.464 10168-10168/org.bytedeco.javacv_android_example W/linker: /data/app/org.bytedeco.javacv_android_example-2/lib/arm/libjniavcodec.so: unused DT entry: type 0xf arg 0x1c7f7
04-25 18:13:37.613 10168-10168/org.bytedeco.javacv_android_example W/linker: /data/app/org.bytedeco.javacv_android_example-2/lib/arm/libjniavformat.so: unused DT entry: type 0xf arg 0x183ce
04-25 18:13:37.744 10168-10168/org.bytedeco.javacv_android_example W/linker: /data/app/org.bytedeco.javacv_android_example-2/lib/arm/libjniswscale.so: unused DT entry: type 0xf arg 0x3f5c
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -113: Could not open 'null'
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:800)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:236)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:315)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.view.View.performClick(View.java:5204)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.view.View$PerformClick.run(View.java:21158)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5461)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-25 18:13:42.348 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err: org.bytedeco.javacv.FrameRecorder$Exception: avio_open2 error() error -113: Could not open 'null'
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.startUnsafe(FFmpegFrameRecorder.java:800)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv.FFmpegFrameRecorder.start(FFmpegFrameRecorder.java:351)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.startRecording(RecordActivity.java:236)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at org.bytedeco.javacv_android_example.record.RecordActivity.onClick(RecordActivity.java:315)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.view.View.performClick(View.java:5204)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.view.View$PerformClick.run(View.java:21158)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
04-25 18:14:16.402 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-25 18:14:16.403 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5461)
04-25 18:14:16.403 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-25 18:14:16.403 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-25 18:14:16.403 10168-10168/org.bytedeco.javacv_android_example W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by saudet** [comment]
Does this happen only on Android? Or does it happen with Java SE as well?

**Comment by Marcrazyness** [comment]
I am having this same issue. @MuthuEphron did you ever resolve this?

**Comment by MuthuEphron** [comment]
@Marcrazyness  No , I didn't it,

**Comment by Nischitha-S** [comment]
Hi,
Iam getting the same error in android studio in linux os. please help me to recover that errror

**Comment by saudet** [comment]
Errno 113 is "No route to host", so it's probably just an issue with the network.

**Comment by Nischitha-S** [comment]
to overcome this what i need to do sir.

Thanks
S.Nischitha

**Comment by Nischitha-S** [comment]
09-08 15:45:23.334 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_core.so: unused DT entry: type 0x1d arg 0x4f533
09-08 15:45:23.524 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_imgproc.so: unused DT entry: type 0x1d arg 0x248c8
09-08 15:45:23.594 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_video.so: unused DT entry: type 0x1d arg 0x604d
09-08 15:45:23.684 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_imgcodecs.so: unused DT entry: type 0x1d arg 0x3b34
09-08 15:45:23.774 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_videoio.so: unused DT entry: type 0x1d arg 0x2752
09-08 15:45:23.874 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_highgui.so: unused DT entry: type 0x1d arg 0x7ef8
09-08 15:45:23.904 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_flann.so: unused DT entry: type 0x1d arg 0x3528
09-08 15:45:23.944 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_ml.so: unused DT entry: type 0x1d arg 0x6a9a
09-08 15:45:24.054 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_features2d.so: unused DT entry: type 0x1d arg 0xabbf
09-08 15:45:24.154 13979-13979/com.example.samuel.videostabilization
W/linker: libjniopencv_calib3d.so: unused DT entry: type 0x1d arg 0xf9fc


Thanks
S.Nischitha

**Comment by Nischitha-S** [comment]
Hi,
    Iam getting the above error sir and it is not at all playing the video
in my device

Thanks
S.Nischitha
