### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: copyPixelsFromBuffer called on recycled bitmap

### ISSUE THREAD

**Issue by Neelchudasama1** [bytedeco/sample-projects#33]
#0. Crashed: Thread-12
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
       at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:598)
       at org.bytedeco.javacv.AndroidFrameConverter.convert(AndroidFrameConverter.java:203)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview.deliverAndDrawFrame(CvCameraPreview.java:816)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview$CameraWorker.run(CvCameraPreview.java:785)
       at java.lang.Thread.run(Thread.java:764)

--

Fatal Exception: java.lang.IllegalStateException: copyPixelsFromBuffer called on recycled bitmap
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
       at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:598)
       at org.bytedeco.javacv.AndroidFrameConverter.convert(AndroidFrameConverter.java:203)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview.deliverAndDrawFrame(CvCameraPreview.java:816)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview$CameraWorker.run(CvCameraPreview.java:785)
       at java.lang.Thread.run(Thread.java:764)

#0. Crashed: Thread-12
       at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
       at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:598)
       at org.bytedeco.javacv.AndroidFrameConverter.convert(AndroidFrameConverter.java:203)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview.deliverAndDrawFrame(CvCameraPreview.java:816)
       at org.bytedeco.javacv.android.recognize.example.CvCameraPreview$CameraWorker.run(CvCameraPreview.java:785)
       at java.lang.Thread.run(Thread.java:764)

**Comment by Neelchudasama1** [comment]
HI. Please let me know if you have any solution for this.

**Comment by saudet** [comment]
Try not to call `recycle()` on the `Bitmap` returned by `AndroidFrameConverter.convert()`.

**Comment by saudet** [comment]
Given the lack of feedback, I'm assuming that not calling `Bitmap.recycle()` fixed this issue, but please let me know if this isn't the case!
