### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.imgcodecs.Imgcodecs.imread_1(java.lang.String)

### ISSUE THREAD

**Issue by Adolphsa** [bytedeco/sample-projects#59]
i run the demo,find it can not  call opencv function.

`2021-10-15 17:17:44.092 32281-32281/org.bytedeco.javacv_android_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.bytedeco.javacv_android_example, PID: 32281
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.imgcodecs.Imgcodecs.imread_1(java.lang.String) (tried Java_org_opencv_imgcodecs_Imgcodecs_imread_11 and Java_org_opencv_imgcodecs_Imgcodecs_imread_11__Ljava_lang_String_2)
        at org.opencv.imgcodecs.Imgcodecs.imread_1(Native Method)
        at org.opencv.imgcodecs.Imgcodecs.imread(Imgcodecs.java:287)
        at org.bytedeco.javacv_android_example.record.RecordActivity.onCreate(RecordActivity.java:94)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

**Comment by Adolphsa** [comment]
thank you  very much!!!
